### ISSUE TITLE
Change icon colors

### ISSUE THREAD

**Issue by guillermo7227** [chteuchteu/MaterialDesignIcons-PHP#1]
Hello. How do I change icon's color?

**Comment by quentin-st** [comment]
Hello! You could either use inline CSS (by providing the `style` tag in the 4th argument), or add fill classes to your stylesheets:

### Inline CSS:
```php
Mdi::mdi('account', null, 24, [
    'style' => 'fill: #2cbe4e'
])
```

### CSS classes
```css
.fill-green {
    fill: #2cbe4e;
}
```

```php
Mdi::mdi('account', 'fill-green')
```
