### ISSUE TITLE
Having issue implementing it on Twig template symfony

### ISSUE THREAD

**Issue by heardofdezz** [chteuchteu/MaterialDesignIcons-PHP#2]
Hey

I have done what the tutorial showed.

Dowloaded mid-php using composer require

i have a symphony extension file : 
```
public function getFunctions()
    {
         return[
            new TwigFunction('mdi', array(Mdi::class, 'mdi', ['is_safe' => ['html']]))
        ];
    }

```

on my view a simple code  : 
`{{ mdi('account', 'fill-muted', 42, {'aria-label': 'My account icon'}) }}`

i get an error when i load my page on the browser : 

`An exception has been thrown during the rendering of a template ("You forgot to specify MDI's path!").`

the error highlights : 
`  {{ mdi('account', 'fill-muted', 42, {'aria-label': 'My account icon'}) }}`

is my mdi() function suppose to take an url path  ?
Thank you, it might be a stupi error from my part but i have working on it for a couple hours and im losing my mind. lol

**Comment by quentin-st** [comment]
Hello!

Did you install the `@mdi/svg` npm package as specified in [this section](https://github.com/chteuchteu/MaterialDesignIcons-PHP#using-mdisvg-npm-package) of the Readme?

```bash
yarn add @mdi/svg

# or, using npm
npm install @mdi/svg
```

**Comment by heardofdezz** [comment]
Yea i did a `yarn add @mdi/svg` and a `composer require mesavolt/mdi-php`

**Comment by heardofdezz** [comment]
Now i got this as an output on my view page : ```
Name of the Theme88

@username Created at : 16/07/20 <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="42" height="42" role="presentation" aria-label="My account icon" class="fill-muted"><path d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" /></svg>
```

**Comment by heardofdezz** [comment]
Name of the Theme88

@username Created at : 16/07/20 <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="42" height="42" role="presentation" aria-label="My account icon" class="fill-muted"><path d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" /></svg>

**Comment by heardofdezz** [comment]
Now i get this as an output. 
![mdi](https://user-images.githubusercontent.com/26879590/87965474-1ac4f800-cabc-11ea-85ef-4bcb24399696.png)

**Comment by heardofdezz** [comment]
@chteuchteu c'est normal comme affichage ou il ya un truc qui me manque ?

**Comment by quentin-st** [comment]
@heardofdezz Comment as-tu enregistré la fonction Twig ?
Comme indiqué [dans la documentation](https://github.com/chteuchteu/MaterialDesignIcons-PHP#plugging-it-to-twig), il est nécessaire de spécifier l'argument `['is_safe' => ['html']]`.

**Comment by heardofdezz** [comment]
![twigextension](https://user-images.githubusercontent.com/26879590/88291546-ae830800-ccf8-11ea-8b15-9edec2afea3b.png)

**Comment by heardofdezz** [comment]
J'ai bien précisé `...['is_safe' => ['html']]))`

**Comment by heardofdezz** [comment]
@chteuchteu

**Comment by quentin-st** [comment]
Pourrais-tu tenter 

```twig
{{ mdi('chevron-left')|raw }}
```

?

**Comment by heardofdezz** [comment]
@chteuchteu   J'ai rajouté` {{ mdi('chevron-left')|raw }}` comme tu me la demandé, il s'affiche bien le svg . 
![chevron](https://user-images.githubusercontent.com/26879590/88816905-32d40000-d1bd-11ea-971c-c303580c49fb.png)

**Comment by heardofdezz** [comment]
@chteuchteu fallait juste que je rajoute l'argument raw :), ca marche now merci
