### ISSUE TITLE
Add option without yarn and composer

### ISSUE THREAD

**Issue by CubicrootXYZ** [chteuchteu/MaterialDesignIcons-PHP#3]
Please add an option to use MDI without yarn or composer.

**Comment by quentin-st** [comment]
As stated [in the documentation](https://github.com/chteuchteu/MaterialDesignIcons-PHP#other), you could use any other option you wish to include the icons. You could download the [@mdi/svg package](https://github.com/Templarian/MaterialDesign-SVG)'s content into your project, and reference their absolute path like this:

```php
Mdi::withIconsPath(__DIR__.'/@mdi/svg/svg/');
```
